name: 'Terraform command'
description: 'Run a terraform command'
inputs:
  command:
    description: 'The command to run'
    required: true
  env:
    description: 'The environment code (eg. dev)'
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    
    - name: Terraform init
      run: terraform init -backend-config ../../configuration/${{ inputs.env }}/backend.hcl
      shell: bash

    - name: Terraform ${{ inputs.command }}
      run: terraform ${{ inputs.command }} -var-file=../../configuration/dev/var.tfvars
      shell: bash
      env: 
        TF_VAR_admin_account_password: ${{ secrets.DB_ACCOUNT_PASSWORD }}