name: 'Terraform command'
description: 'Run a terraform command'
inputs:
  command:
    description: 'The command to run'
    required: true
  env:
    description: 'The environment code (eg. dev)'
    required: true
  db-account-password:
    description: 'The sql admin password'
runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    
    - name: Terraform init
      run: cd ${{ github.action_path }} && terraform init -backend-config ../../configuration/${{ inputs.env }}/backend.hcl
      shell: bash

    - name: Terraform ${{ inputs.command }}
      run: cd ${{ github.action_path }} && terraform ${{ inputs.command }} -var-file=../../configuration/${{ inputs.env }}/var.tfvars
      shell: bash
      env: 
        TF_VAR_admin_account_password: ${{ inputs.db-account-password }}