name: 'Terraform CD'

on: push

defaults:
  run:
    working-directory: src/terraform

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout
      uses: actions/Checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    
    - name: Terraform init
      run: terraform init -backend-config ../../configuration/dev/backend.hcl

    - name: Terraform plan
      run: terraform plan -var-file=../../configuration/dev/var.tfvars
      env: 
        TF_VAR_ADMIN_ACCOUNT_PASSWORD: ${{ secrets.DB_ACCOUNT_PASSWORD }}
