name: 'Terraform CD'

on: push

defaults:
  run:
    working-directory: src/terraform

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

jobs:
  plan_dev:
    name: '[Dev] Plan'
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/Checkout@v3

      - uses: .github/actions/terraform
        with:
          command: 'plan'
          env: 'dev'
          db-account-password: '${{ secrets.DB_ACCOUNT_PASSWORD }}'

